import type { AuditReport, FindingGroup } from "../report-schema.js";
import { capitalize, instancesLabel, summaryLine, wcagLabel } from "./shared.js";

/** Elements listed per group; the JSON report always has all of them. */
const MAX_ELEMENTS_PER_GROUP = 5;

/** Escapes text placed inside a table cell or a paragraph. The audited page controls it. */
function escapeInline(text: string): string {
  return text
    .replace(/[\\`*_{}[\]<>|#]/g, (char) => `\\${char}`)
    .replace(/\s+/g, " ")
    .trim();
}

/** Wraps code in a fence longer than any backtick run it contains, so it cannot break out. */
function codeBlock(code: string, language: string): string {
  const longestRun = Math.max(0, ...(code.match(/`+/g) ?? []).map((run) => run.length));
  const fence = "`".repeat(Math.max(3, longestRun + 1));
  return `${fence}${language}\n${code}\n${fence}`;
}

function inlineCode(code: string): string {
  const longestRun = Math.max(0, ...(code.match(/`+/g) ?? []).map((run) => run.length));
  const fence = "`".repeat(longestRun + 1);
  const padding = code.startsWith("`") || code.endsWith("`") ? " " : "";
  return `${fence}${padding}${code.replace(/\s+/g, " ")}${padding}${fence}`;
}

function groupSection(group: FindingGroup): string {
  const { rule, findings } = group;
  const lines = [
    `### ${escapeInline(rule.help)}`,
    "",
    `**${capitalize(group.impact)}** · ${wcagLabel(rule)} · ${instancesLabel(group)} · rule [\`${rule.id}\`](${rule.helpUrl})`,
    "",
    escapeInline(rule.description),
    "",
  ];

  for (const finding of findings.slice(0, MAX_ELEMENTS_PER_GROUP)) {
    lines.push(`- ${inlineCode(finding.selector)}`, "");
    lines.push(
      codeBlock(finding.htmlTruncated ? `${finding.html}…` : finding.html, "html")
        .split("\n")
        .map((line) => `  ${line}`)
        .join("\n"),
      "",
    );
  }
  if (findings.length > MAX_ELEMENTS_PER_GROUP) {
    lines.push(`…and ${findings.length - MAX_ELEMENTS_PER_GROUP} more with the same pattern.`, "");
  }
  return lines.join("\n");
}

export function formatMarkdown(report: AuditReport): string {
  const { summary, target } = report;
  const lines = [
    "# Allytic accessibility report",
    "",
    `**Target:** ${escapeInline(target.url)}${target.title ? ` (${escapeInline(target.title)})` : ""}  `,
    `**Checked against:** ${report.standard} rules of ${report.engine.name} ${report.engine.version}  `,
    `**Generated:** ${report.generatedAt}`,
    "",
    `> ${report.disclaimer}`,
    "",
    "## Summary",
    "",
    `${capitalize(summaryLine(report))}.`,
    "",
  ];

  if (summary.findings > 0) {
    lines.push(
      "| Impact | Issue | WCAG | Elements |",
      "| --- | --- | --- | ---: |",
      ...report.groups.map(
        (group) =>
          `| ${capitalize(group.impact)} | ${escapeInline(group.rule.help)} | ${wcagLabel(group.rule)} | ${group.findings.length} |`,
      ),
      "",
      "## Issues",
      "",
      ...report.groups.map(groupSection),
    );
  }

  if (report.needsReview.length > 0) {
    lines.push(
      "## Needs manual review",
      "",
      "axe-core could not decide these checks automatically. They are not counted as issues.",
      "",
      ...report.needsReview.map(
        (group) =>
          `- ${escapeInline(group.rule.help)} — ${instancesLabel(group)} (rule [\`${group.rule.id}\`](${group.rule.helpUrl}))`,
      ),
      "",
    );
  }

  lines.push("---", "", `Generated by ${report.tool.name} ${report.tool.version}.`, "");
  return lines.join("\n");
}
