import type { AuditReport, FindingGroup, Suggestion } from "../report-schema.js";
import {
  aiNotice,
  capitalize,
  instancesLabel,
  patchScopeNote,
  ruleRows,
  summaryLine,
  verificationLabel,
  wcagLabel,
} from "./shared.js";

/** Elements listed per group; the JSON report always has all of them. */
const MAX_ELEMENTS_PER_GROUP = 5;

/** Escapes text placed inside a table cell or a paragraph. The audited page controls it. */
function escapeInline(text: string): string {
  return text
    .replace(/[\\`*_{}[\]<>|#]/g, (char) => `\\${char}`)
    .replace(/\s+/g, " ")
    .trim();
}

function longestBacktickRun(code: string): number {
  return Math.max(0, ...(code.match(/`+/g) ?? []).map((run) => run.length));
}

/** Wraps code in a fence longer than any backtick run it contains, so it cannot break out. */
function codeBlock(code: string, language: string, indent = ""): string {
  const fence = "`".repeat(Math.max(3, longestBacktickRun(code) + 1));
  return [`${fence}${language}`, ...code.split("\n"), fence]
    .map((line) => `${indent}${line}`.trimEnd())
    .join("\n");
}

function inlineCode(code: string): string {
  const fence = "`".repeat(longestBacktickRun(code) + 1);
  const padding = code.startsWith("`") || code.endsWith("`") ? " " : "";
  return `${fence}${padding}${code.replace(/\s+/g, " ")}${padding}${fence}`;
}

function suggestionSection(suggestion: Suggestion): string[] {
  const lines = [
    `**Why it matters:** ${escapeInline(suggestion.explanation)}`,
    "",
    `**Who is affected:** ${escapeInline(suggestion.affects)}`,
    "",
  ];
  const { patch } = suggestion;
  if (patch) {
    const { status, sentence } = verificationLabel(patch);
    const note = patchScopeNote(patch);
    lines.push(
      `**Suggested fix for ${inlineCode(patch.selector)} — ${status}.** ${escapeInline(sentence)}${note ? ` ${note}` : ""}`,
      "",
      "Before:",
      "",
      codeBlock(patch.before, "html"),
      "",
      "After:",
      "",
      codeBlock(patch.after, "html"),
      "",
    );
  }
  return lines;
}

function groupSection(group: FindingGroup): string {
  const { rule, findings } = group;
  const lines = [
    `### ${escapeInline(rule.help)}`,
    "",
    `**${capitalize(group.impact)}** · ${wcagLabel(rule)} · ${instancesLabel(group)} · rule [\`${rule.id}\`](${rule.helpUrl})`,
    "",
    escapeInline(rule.description),
    "",
  ];

  if (group.suggestion) lines.push(...suggestionSection(group.suggestion));

  for (const finding of findings.slice(0, MAX_ELEMENTS_PER_GROUP)) {
    lines.push(
      `- ${inlineCode(finding.selector)}`,
      "",
      codeBlock(finding.htmlTruncated ? `${finding.html}…` : finding.html, "html", "  "),
      "",
    );
  }
  if (findings.length > MAX_ELEMENTS_PER_GROUP) {
    lines.push(`…and ${findings.length - MAX_ELEMENTS_PER_GROUP} more with the same pattern.`, "");
  }
  return lines.join("\n");
}

export function formatMarkdown(report: AuditReport): string {
  const { summary, target } = report;
  const notice = aiNotice(report);
  const lines = [
    "# Allytic accessibility report",
    "",
    `**Target:** ${escapeInline(target.url)}${target.title ? ` (${escapeInline(target.title)})` : ""}  `,
    `**Checked against:** ${report.standard} rules of ${report.engine.name} ${report.engine.version}  `,
    `**Generated:** ${report.generatedAt}`,
    "",
    `> ${report.disclaimer}`,
    "",
    ...(notice ? [`> ${notice}`, ""] : []),
    "## Summary",
    "",
    `${capitalize(summaryLine(report))}.`,
    "",
  ];

  if (summary.findings > 0) {
    lines.push(
      "| Impact | Issue | WCAG | Elements |",
      "| --- | --- | --- | ---: |",
      ...ruleRows(report.groups).map(
        (row) =>
          `| ${capitalize(row.impact)} | ${escapeInline(row.rule.help)} | ${wcagLabel(row.rule)} | ${row.elements} |`,
      ),
      "",
      "## Issues",
      "",
      ...report.groups.map(groupSection),
    );
  }

  if (report.needsReview.length > 0) {
    lines.push(
      "## Needs manual review",
      "",
      "axe-core could not decide these checks automatically. They are not counted as issues.",
      "",
      ...report.needsReview.map(
        (group) =>
          `- ${escapeInline(group.rule.help)} — ${instancesLabel(group)} (rule [\`${group.rule.id}\`](${group.rule.helpUrl}))`,
      ),
      "",
    );
  }

  lines.push("---", "", `Generated by ${report.tool.name} ${report.tool.version}.`, "");
  return lines.join("\n");
}
